### ISSUE TITLE
Puma issue

### ISSUE THREAD

**Issue by nwshane** [JumpStartGeorgia/Azerbaijan-Political-Prisoners#311]
Deploying to production resulted in:
- Broke the site; only plain HTML was being shown
- `mina puma:stop` -> `Puma is not running!` error
- `mina puma:start` caused error:

```
[3443] * Listening on unix:///home/prisoners/Prisoners/tmp/puma/sockets/puma.sock
/home/prisoners/Prisoners/releases/8/vendor/bundle/ruby/2.1.0/gems/puma-2.11.3/lib/puma/binder.rb:284:in `add_unix_listener': There is already a server bound to: /home/prisoners/Prisoners/tmp/puma/sockets/puma.sock (RuntimeError)
	from /home/prisoners/Prisoners/releases/8/vendor/bundle/ruby/2.1.0/gems/puma-2.11.3/lib/puma/binder.rb:124:in `block in parse'
	from /home/prisoners/Prisoners/releases/8/vendor/bundle/ruby/2.1.0/gems/puma-2.11.3/lib/puma/binder.rb:82:in `each'
	from /home/prisoners/Prisoners/releases/8/vendor/bundle/ruby/2.1.0/gems/puma-2.11.3/lib/puma/binder.rb:82:in `parse'
	from /home/prisoners/Prisoners/releases/8/vendor/bundle/ruby/2.1.0/gems/puma-2.11.3/lib/puma/runner.rb:119:in `load_and_bind'
	from /home/prisoners/Prisoners/releases/8/vendor/bundle/ruby/2.1.0/gems/puma-2.11.3/lib/puma/cluster.rb:302:in `run'
	from /home/prisoners/Prisoners/releases/8/vendor/bundle/ruby/2.1.0/gems/puma-2.11.3/lib/puma/cli.rb:216:in `run'
	from /home/prisoners/Prisoners/releases/8/vendor/bundle/ruby/2.1.0/gems/puma-2.11.3/bin/puma:10:in `<top (required)>'
	from /home/prisoners/Prisoners/releases/8/vendor/bundle/ruby/2.1.0/bin/puma:23:in `load'
	from /home/prisoners/Prisoners/releases/8/vendor/bundle/ruby/2.1.0/bin/puma:23:in `<main>'
```

Workaround:

1) Following puma files have been removed: 
- `~/Prisoners/tmp/puma/state`
- `~/Prisoners/tmp/puma/pid`
- `~/Prisoners/tmp/puma/sockets/pumactl.sock`

2) Only file remaining is `~/Prisoners/tmp/puma/sockets/puma.sock`. Remove this file

3) Run `mina production puma:start`

Changes made so far:
- Removed `preload_app!` from puma config because it does not play nicely with phased_restart command (see bottom of this section: https://github.com/puma/puma#clustered-mode)
- Tried configuring puma to use SSL, according to this section: https://github.com/puma/puma#binding-tcp--sockets.  Could not get this to work, and decided that it's better to leave SSL to Nginx after reading this: http://stackoverflow.com/a/15400260/3115911
- Changed location of config files from shared to current folder on server, which fixed rollback and may have fixed other things as well.

To-do:
- Investigate on_restart hook (https://github.com/puma/puma#cleanup-code); see if anyone has posted some general code that might reduce chance of memory leaks.

**Comment by nwshane** [comment]
`mina puma:stop` causes `Puma is not running!` error because the pumactl socket does not exist anymore, which triggers that error.

**Comment by nwshane** [comment]
`mina puma:start` causes the `There is already a server bound to:` error because of the following code:

```
def add_unix_listener(path, umask=nil, mode=nil)
  @unix_paths << path

  # Let anyone connect by default
  umask ||= 0

  begin
    old_mask = File.umask(umask)

    if File.exist? path
      begin
        old = UNIXSocket.new path
      rescue SystemCallError, IOError
        File.unlink path
      else
        old.close
        raise "There is already a server bound to: #{path}"
      end
    end
```
