### ISSUE TITLE
puma error "There is already a server bound to"

### ISSUE THREAD

**Issue by nwshane** [JumpStartGeorgia/Azerbaijan-Political-Prisoners#316]
```
nathan-shanes-macbook-2:azeriPrisonersVis django09$ mina deploy
Connection to alpha.jumpstart.ge closed.
-----> Assets unchanged; skipping precompile assets
-----> Loading rbenv        
-----> Creating a temporary build path        
-----> Fetching new git commits        
       From github.com:JumpStartGeorgia/Azerbaijan-Political-Prisoners
       556cc65..61e23ff  master     -> master
-----> Using git branch 'master'        
       Cloning into '.'... 
       done. 
-----> Using this git commit        
       
       nwshane (61e23ff): 
       > Removing generated files after specs. 
       
-----> Symlinking shared paths        
-----> Installing gem dependencies using Bundler        
-----> DB migrations unchanged; skipping DB migration        
-----> Copying assets from tmp/assets to current/public/assets        
-----> Generating SSL Nginx Config file        
-----> Copying new nginx.conf to: /home/prisoners-staging/Azeri-Prisoners-Staging/tmp/build-14345241078855/config/nginx.conf        
-----> Generating new config/puma.rb        
-----> Copying new puma.rb to: /home/prisoners-staging/Azeri-Prisoners-Staging/tmp/build-14345241078855/config/puma.rb        
-----> Cleaning up old releases (keeping 5)        
-----> Build finished        
-----> Moving build to releases/100        
-----> Updating the current symlink        
-----> Launching        
       Command stop sent success 
       [13372] Puma starting in cluster mode... 
       [13372] * Version 2.11.3 (ruby 2.1.2-p95), codename: In       /home/prisoners-staging/Azeri-Prisoners-Staging/releases/100/vendor/bundle/ruby/2.1.0/gems/puma-2.11.3/lib/puma/binder.rb:284:in `add_unix_listener': There is already a server bound to: /home/prisoners-staging/Azeri-Prisoners-Staging/tmp/puma/sockets/puma.sock (RuntimeError)
tr       from /home/prisoners-staging/Azeri-Prisoners-Staging/releases/100/vendor/bundle/ruby/2.1.0/gems/puma-2.11.3/lib/puma/binder.rb:124:in `block in parse'
e       from /home/prisoners-staging/Azeri-Prisoners-Staging/releases/100/vendor/bundle/ruby/2.1.0/gems/puma-2.11.3/lib/puma/binder.rb:82:in `each'
p       from /home/prisoners-staging/Azeri-Prisoners-Staging/releases/100/vendor/bundle/ruby/2.1.0/gems/puma-2.11.3/lib/puma/binder.rb:82:in `parse'
i       from /home/prisoners-staging/Azeri-Prisoners-Staging/releases/100/vendor/bundle/ruby/2.1.0/gems/puma-2.11.3/lib/puma/cluster.rb:325:in `run'
       [13372] * Version 2.11.3 (ruby 2.1.2-p95), codename: Intrepid Squirrel
       from /home/prisoners-staging/Azeri-Prisoners-Staging/releases/100/vendor/bundle/ruby/2.1.0/gems/puma-2.11.3/lib/puma/cli.rb:216:in `run'
       [133       from /home/prisoners-staging/Azeri-Prisoners-Staging/releases/100/vendor/bundle/ruby/2.1.0/gems/puma-2.11.3/bin/puma:10:in `<top (required)>'
7       from /home/prisoners-staging/Azeri-Prisoners-Staging/releases/100/vendor/bundle/ruby/2.1.0/bin/puma:23:in `load'
2]        from /home/prisoners-staging/Azeri-Prisoners-Staging/releases/100/vendor/bundle/ruby/2.1.0/bin/puma:23:in `<main>'
       [13372] * Min threads: 2, max threads: 4
       [13372] * Environment: staging 
       [13372] * Process workers: 2 
       [13372] * Phased restart available 
       [13372] * Listening on unix:///home/prisoners-staging/Azeri-Prisoners-Staging/tmp/puma/sockets/puma.sock 
 !     ERROR: Deploy failed.   
-----> Cleaning up build        
       Deleting release 
       Unlinking current 
       OK 

 !     Command failed.
       Failed with status 19
```

puma.access.log:

```
/home/prisoners-staging/Azeri-Prisoners-Staging/releases/99/vendor/bundle/ruby/2.1.0/gems/puma-2.11.3/lib/puma/binder.rb:44:in `unlink': No such file or directory @ unlink_internal - /home/prisoners-staging/Azeri-Prisoners-Staging/tmp/puma/sockets/pumactl.sock (Errno::ENOENT)
	from /home/prisoners-staging/Azeri-Prisoners-Staging/releases/99/vendor/bundle/ruby/2.1.0/gems/puma-2.11.3/lib/puma/binder.rb:44:in `block in close'
	from /home/prisoners-staging/Azeri-Prisoners-Staging/releases/99/vendor/bundle/ruby/2.1.0/gems/puma-2.11.3/lib/puma/binder.rb:44:in `each'
	from /home/prisoners-staging/Azeri-Prisoners-Staging/releases/99/vendor/bundle/ruby/2.1.0/gems/puma-2.11.3/lib/puma/binder.rb:44:in `close'
	from /home/prisoners-staging/Azeri-Prisoners-Staging/releases/99/vendor/bundle/ruby/2.1.0/gems/puma-2.11.3/lib/puma/server.rb:338:in `handle_servers'
	from /home/prisoners-staging/Azeri-Prisoners-Staging/releases/99/vendor/bundle/ruby/2.1.0/gems/puma-2.11.3/lib/puma/server.rb:284:in `block in run'
```

Other info:
- Puma was no longer running after this deploy when checked with htop on server.

**Comment by nwshane** [comment]
puma.access.log:

```
/home/prisoners-staging/Azeri-Prisoners-Staging/releases/99/vendor/bundle/ruby/2.1.0/gems/puma-2.11.3/lib/puma/binder.rb:44:in `unlink': No such file or directory @ unlink_internal - /home/prisoners-staging/Azeri-Prisoners-Staging/tmp/puma/sockets/pumactl.sock (Errno::ENOENT)
	from /home/prisoners-staging/Azeri-Prisoners-Staging/releases/99/vendor/bundle/ruby/2.1.0/gems/puma-2.11.3/lib/puma/binder.rb:44:in `block in close'
	from /home/prisoners-staging/Azeri-Prisoners-Staging/releases/99/vendor/bundle/ruby/2.1.0/gems/puma-2.11.3/lib/puma/binder.rb:44:in `each'
	from /home/prisoners-staging/Azeri-Prisoners-Staging/releases/99/vendor/bundle/ruby/2.1.0/gems/puma-2.11.3/lib/puma/binder.rb:44:in `close'
	from /home/prisoners-staging/Azeri-Prisoners-Staging/releases/99/vendor/bundle/ruby/2.1.0/gems/puma-2.11.3/lib/puma/server.rb:338:in `handle_servers'
	from /home/prisoners-staging/Azeri-Prisoners-Staging/releases/99/vendor/bundle/ruby/2.1.0/gems/puma-2.11.3/lib/puma/server.rb:284:in `block in run'
```

**Comment by nwshane** [comment]
Possible workaround: Delete puma.sock either 1) after stopping puma or 2) before starting puma. This will prevent the `There is already a server bound to` error, but it may lead to other problems; for example, if there is still a process running on that socket, the process will be left open.

For now, I won't implement the above workaround, and I won't deploy to production. Instead, I'll continue deploying to staging to see if this happens again, so that I can gather more data on this issue and try to reproduce it.

**Comment by nwshane** [comment]
Happened again.

```
nathan-shanes-macbook-2:azeriPrisonersVis django09$ mina deploy
Connection to alpha.jumpstart.ge closed.
-----> Assets unchanged; skipping precompile assets
-----> Loading rbenv        
-----> Creating a temporary build path        
-----> Fetching new git commits        
       From github.com:JumpStartGeorgia/Azerbaijan-Political-Prisoners
       61e23ff..8c2dbe4  master     -> master
-----> Using git branch 'master'        
       Cloning into '.'... 
       done. 
-----> Using this git commit        
       
       nwshane (8c2dbe4): 
       > Removing tags from all descriptions in CSV output. 
       
-----> Symlinking shared paths        
-----> Installing gem dependencies using Bundler        
-----> Migrating database        
-----> Copying assets from tmp/assets to current/public/assets        
-----> Generating SSL Nginx Config file        
-----> Copying new nginx.conf to: /home/prisoners-staging/Azeri-Prisoners-Staging/tmp/build-143461532924281/config/nginx.conf        
-----> Generating new config/puma.rb        
-----> Copying new puma.rb to: /home/prisoners-staging/Azeri-Prisoners-Staging/tmp/build-143461532924281/config/puma.rb        
-----> Cleaning up old releases (keeping 5)        
-----> Build finished        
-----> Moving build to releases/101        
-----> Updating the current symlink        
-----> Launching        
       Command stop sent success 
       [12802] Puma starting in cluster mode... 
       [12802] * Version 2.11.3 (ruby 2.1.2-p95), codename: Intrepid Squirrel 
       /home/prisoners-staging/Azeri-Prisoners-Staging/releases/101/vendor/bundle/ruby/2.1.0/gems/puma-2.11.3/lib/puma/binder.rb:284:in `add_unix_listener': There is already a server bound to: /home/prisoners-staging/Azeri-Prisoners-Staging/tmp/puma/sockets/puma.sock (RuntimeError)
       from /home/prisoners-staging/Azeri-Prisoners-Staging/releases/101/vendor/bundle/ruby/2.1.0/gems/puma-2.11.3/lib/puma/binder.rb:124:in `block in parse'
       [128       from /home/prisoners-staging/Azeri-Prisoners-Staging/releases/101/vendor/bundle/ruby/2.1.0/gems/puma-2.11.3/lib/puma/binder.rb:82:in `each'
       [12802] * Min threads: 2, max threads: 4
       from /home/prisoners-staging/Azeri-Prisoners-Staging/releases/101/vendor/bundle/ruby/2.1.0/gems/puma-2.11.3/lib/puma/binder.rb:82:in `parse'
       [12802] * Environment: staging
       [       from /home/prisoners-staging/Azeri-Prisoners-Staging/releases/101/vendor/bundle/ruby/2.1.0/gems/puma-2.11.3/lib/puma/cluster.rb:325:in `run'
12802] *       from /home/prisoners-staging/Azeri-Prisoners-Staging/releases/101/vendor/bundle/ruby/2.1.0/gems/puma-2.11.3/lib/puma/cli.rb:216:in `run'
       from /home/prisoners-staging/Azeri-Prisoners-Staging/releases/101/vendor/bundle/ruby/2.1.0/gems/puma-2.11.3/bin/puma:10:in `<top (required)>'
 Proc       from /home/prisoners-staging/Azeri-Prisoners-Staging/releases/101/vendor/bundle/ruby/2.1.0/bin/puma:23:in `load'
ess worker       from /home/prisoners-staging/Azeri-Prisoners-Staging/releases/101/vendor/bundle/ruby/2.1.0/bin/puma:23:in `<main>'
       [12802] * Process workers: 2
       [12802] * Phased restart available 
       [12802] * Listening on unix:///home/prisoners-staging/Azeri-Prisoners-Staging/tmp/puma/sockets/puma.sock 
 !     ERROR: Deploy failed.   
-----> Cleaning up build        
       Deleting release 
       Unlinking current 
       OK 

 !     Command failed.
       Failed with status 19
```

Contents of puma folder on server:
```
./state
./sockets
./sockets/puma.sock
```

**Comment by nwshane** [comment]
Filed puma issue report here: https://github.com/puma/puma/issues/713
